name: Build and deploy to IPFS

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    if: |
      (github.event_name == 'push' && github.ref == 'refs/heads/main') ||
      (github.event.pull_request.head.repo.full_name == github.event.pull_request.base.repo.full_name &&
      !contains(github.head_ref, 'dependabot'))
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          persist-credentials: false

      - name: Build App
        uses: ./.github/actions/build
        with:
          NEXT_PUBLIC_ENV: 'prod'

      - name: Upload artifacts
        uses: ./.github/actions/upload-artifacts
        with:
          BUILD_ARTIFACT_NAME: 'out'

  build_staging:
    runs-on: ubuntu-latest
    if: |
      github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0
        with:
          persist-credentials: false

      - name: Build App
        uses: ./.github/actions/build
        with:
          NEXT_PUBLIC_ENV: 'staging'

      - name: Upload artifacts
        uses: ./.github/actions/upload-artifacts
        with:
          BUILD_ARTIFACT_NAME: 'out_staging'
          NEXTJS_BUILD: 'false'
          PR_INFO: 'false'

  next_js_analyze:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - name: download build
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
        with:
          name: nextjs_build
          path: .next

      - uses: ./.github/actions/analyze-comment
        if: github.event_name != 'pull_request'

      - uses: ./.github/actions/analyze-comment
        if: github.event_name == 'pull_request'
        with:
          PULL_REQUEST_NUMBER: ${{ github.event.number }}

  deploy:
    runs-on: ubuntu-latest
    needs:
      - build
    outputs:
      pinata_hash: '${{ steps.pinata.outputs.hash }}'
    steps:
      - uses: actions/checkout@a12a3943b4bdde767164f792f33f40b04645d846 # v3.0.0

      - name: download build
        uses: actions/download-artifact@fb598a63ae348fa914e94cd0ff38f362e927b741 # v3.0.0
        with:
          name: out
          path: out

      - name: pinata
        id: pinata
        uses: aave/pinata-action@b03be403ea86f79077ea9cc0b835c3295faa12dd
        with:
          PINATA_API_KEY: ${{ secrets.PINATA_API_KEY }}
          PINATA_SECRET_KEY: ${{ secrets.PINATA_SECRET_KEY }}
          PIN_ALIAS: 'app-aave-${{ github.head_ref || github.ref }}'
          BUILD_LOCATION: './out'
          CID_VERSION: 1
